FROM wazoplatform/wazo-auth-cli

ENV PYTHONDONTWRITEBYTECODE='true'

COPY . /usr/src/wazo-auth-keys

WORKDIR /usr/src/wazo-auth-keys
RUN python3 -m pip install -e .

RUN true \
    && mkdir -p /etc/wazo-auth-keys/conf.d \
    && mkdir -p /var/lib/wazo-auth-keys \
    && ln -s /usr/local/bin/wazo-auth-cli /usr/bin/wazo-auth-cli \
    && adduser --quiet --system my-custom-user

ENTRYPOINT ["./integration_tests/entrypoint.sh"]
